version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Install uv for fast dependency management
      - pip install uv
      # Install docs dependencies from pyproject.toml
      - uv pip install --system -e ".[docs]"
    post_build:
      # Build docs manually with our installed mkdocs
      - mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html