site_name: Graphio
site_url: https://graphio.readthedocs.io/en/latest/
theme:
  name: material
  features:
    # Navigation
    - navigation.path
    - navigation.sections  
    - navigation.indexes
    - navigation.top        # Back to top button
    - navigation.footer     # Previous/next navigation
    # - navigation.tabs     # Uncomment for top-level tabs
    
    # Search
    - search.highlight      # Highlight search terms
    - search.suggest        # Search suggestions
    
    # Content
    - content.code.copy     # Copy code blocks
    - content.code.annotate # Code annotations
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

repo_url: https://github.com/kaiserpreusse/graphio
repo_name: kaiserpreusse/graphio
edit_uri: edit/master/docs/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kaiserpreusse/graphio
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/graphio/

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  # Table of contents
  - toc:
      permalink: true
      toc_depth: 3
  
  # Code highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
  # Content enhancements  
  - admonition              # !!! info blocks
  - pymdownx.details        # ??? collapsible blocks
  - pymdownx.tabbed:        # === "Tab" blocks
      alternate_style: true
  - pymdownx.keys           # ++ctrl+c++ keyboard keys
  - pymdownx.mark           # ==highlighted== text
  - pymdownx.critic         # {>>comments<<} and edits
  
  # Lists and formatting
  - def_list                # Definition lists
  - footnotes               # [^1] footnotes
  - md_in_html             # Markdown in HTML blocks
  - tables                 # GitHub-style tables
  - attr_list              # {: .class} attributes
nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting_started/index.md
      - OGM Track: getting_started/ogm.md
      - Bulk Loading Track: getting_started/bulk.md
      - Hybrid Approach: getting_started/hybrid.md
  - User Guide:
      - OGM: details/ogm.md
      - Bulk Loading: details/bulk.md
  - API Reference:
      - NodeSet: api_reference/nodeset.md
      - RelationshipSet: api_reference/relationshipset.md
      - NodeModel: api_reference/nodemodel.md
      - Relationship: api_reference/relationship.md
      - Base: api_reference/base.md
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          allow_inspection: true
          docstring_style: sphinx
          show_source: false
          show_root_heading: true
          show_root_full_path: false
          show_category_heading: false
          show_symbol_type_heading: false
          show_symbol_type_toc: true
          members_order: source
          group_by_category: false
          show_signature: true
          show_signature_annotations: true
          separate_signature: true
          line_length: 80
          merge_init_into_class: true
          show_if_no_docstring: false
          heading_level: 2