site_name: Graphio
site_url: https://graphio.readthedocs.io/en/latest/
theme:
  name: material
  features:
    - navigation.path
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences