version: '3.8'
services:
  test_neo4j_42:
    image: neo4j/neo4j-arm64-experimental:4.2.11-arm64
    container_name: graphio_test_neo4j_42
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    ports:
      - 10687:7687
      - 10474:7474
  test_neo4j_43:
    image: neo4j/neo4j-arm64-experimental:4.3.7-arm64
    container_name: graphio_test_neo4j_43
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    ports:
      - 11687:7687
      - 11474:7474
  test_neo4j_44:
    image: neo4j:4.4
    container_name: graphio_test_neo4j_44
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    ports:
      - 12687:7687
      - 12474:7474
  test_neo4j_51:
    image: neo4j:5.1
    container_name: graphio_test_neo4j_51
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    ports:
      - 13687:7687
      - 13474:7474