version: '3.8'
services:
  test_neo4j_35:
    image: neo4j:3.5
    container_name: graphio_test_neo4j_35
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    ports:
      - 8687:7687
      - 8474:7474
  test_neo4j_41:
    image: neo4j:4.1
    container_name: graphio_test_neo4j_41
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    ports:
      - 9687:7687
      - 9474:7474
  test_neo4j_42:
    image: neo4j:4.2
    container_name: graphio_test_neo4j_42
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    ports:
      - 10687:7687
      - 10474:7474
  test_neo4j_43:
    image: neo4j:4.3
    container_name: graphio_test_neo4j_43
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    ports:
      - 11687:7687
      - 11474:7474