name: Build Documentation

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RUN_ENVIRONMENT: 'github_actions'

    container: 'python:3.8'

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
    - name: build documentation
      run: |
        sphinx make html
