name: Build Documentation

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RUN_ENVIRONMENT: 'github_actions'

    container: 'python:3.8'

    steps:
    - uses: actions/checkout@v2
    - name: install system dependencies
      run: |
        apt-get update -y
        apt-get install -y sshpass
    - name: install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f test_requirements.txt ]; then pip install -r test_requirements.txt; fi
    - name: build documentation
      run: |
        sphinx-build -b html docs output
        sshpass -p ${{ secrets.DOCS_SSH_PASSWORD }} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r output/* ${{ secrets.DOCS_SSH_PATH }}
